name: 'Terraform'

on:
  push:
    branches: [ "master" ]

jobs:
  checkout:
    name: 'Code Checkout Repository'
    runs-on: terraform_runner
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

  setup-aws:
    name: 'Configure AWS Credentials'
    runs-on: terraform_runner
    needs: checkout
    steps:
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

  setup-terraform:
    name: 'Setup Terraform'
    runs-on: terraform_runner
    needs: [checkout, setup-aws]
    steps:
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.6'

  terraform-init:
    name: 'Terraform Init'
    runs-on: terraform_runner
    needs: setup-terraform
    steps:
      - name: Terraform Init
        run: terraform init

  terraform-fmt:
    name: 'Terraform Format Check'
    runs-on: terraform_runner
    needs: terraform-init
    steps:
      - name: Terraform Format (Auto-fix)
        run: terraform fmt -recursive

      - name: Terraform Format Check
        run: terraform fmt -check
        
  terraform-validate:
    name: 'Terraform Validate'
    runs-on: terraform_runner
    needs: terraform-fmt
    steps:
      - name: Terraform Validate
        run: terraform validate